### ISSUE TITLE
Errors returned to cmdliner are not reported

### ISSUE THREAD

**Issue by talex5** [dinosaure/hxd#6]
The binaries in this project use `let () = Term.(exit @@ eval cmd)`, where `cmd` has type ``[> `Error of [ `Msg of string ] | `Ok of unit ] t * info``.

However, `Term.exit` will ignore this value and any error returned will go unreported, and the exit status will be success.

e.g. if you change

```ocaml
  let res = Hxd_unix.o configuration ic oc seek null in
```

to

```ocaml
  ignore (Hxd_unix.o, configuration, ic, oc, seek, null);
  let res = Error (`Msg "Failure!") in
```

and run it, no error is reported.

(see https://github.com/dbuenzli/cmdliner/pull/124)

**Comment by dinosaure** [comment]
Close yb #7
